### ISSUE TITLE
Add CardDav support

### ISSUE THREAD

**Issue by toehold** [ubports/address-book-app#3]
Add Carddav support so Contacts can be synced with Owncloud/Nextcloud or any other Carddav Server.

**Comment by userj** [comment]
This seems to be the workaround
https://wiki.ubports.com/wiki/Configure-CalDAV%2BCardDAV-synchronisation

So is it just a matter of creating a graphical input for this?

**Comment by NeoTheThird** [comment]
@userj No. There needs to be a proper gui for managing remote servers, it should not simply be a wrapper for the script. Probably interesting to check out https://github.com/ubports/sync-monitor/pull/1

**Comment by Danfro** [comment]
Hi, it is now one year since the last comment. :-)
With 16.04 it is possible to sync nextcloud calendars.
That works with a nextcloud account created in system settings.
I wonder if that could be possible with contacts as well?
There are already options to add contacts from google and sim-card.
One would expect to have nextcloud added there as well.

**Comment by obacht8** [comment]
Hi, 
a generic CardDAV-account would be great to have, just as it is available for CalDAV already.
Being a GUI-dependant dummy-user myself (nexus 5 OTA 5), the lack of that option is what keeps me from seriously considering daily use of UT.

**Comment by userj** [comment]
@Danfro @obacht8 Thanks for your comment on this. It is valuable feedback for the next steps here. I wish I had the skills to fix this issue. Maybe @mardy can help to point us in the right direction.

**Comment by obacht8** [comment]
@mardy Many thanks!
The coding side of it is way beyond my understanding but it´s great to see that things are on their way!

**Comment by HansjoergN** [comment]
please can anybody make carddav the standard for ubuntu touch? google is the reason to use an alternative OS, so please can we focus on alternative solutions..

**Comment by userj** [comment]
@HansjoergN It sounds like @mardy has a plan for this.

**Comment by ferrettim** [comment]
any updates on this? import from google seems to not work, tried the script for webdav and that doesn't work either.

**Comment by idekovets** [comment]
I think, CardDAV look better than Google Contacts for ideology of Ubuntu Touch.

> Ubuntu Touch: a safer, beautiful, free and open source mobile Operating System

**Comment by Thatoo** [comment]
Any news @mardy on this work?

**Comment by ilmaisin** [comment]
This is becoming silly. Is there any estimate on how much of work this would be. Would a bounty help?

**Comment by Danfro** [comment]
I don't think silly is the right word. If it would be simple, someone would have done it already. ;-) And from what I hear, not even the script works reliable. 

But as one step towards solving this, answering your question might help:

**What needs to be done to implement carddav support for UT?**

Maybe someone here can answer this question who knows what needs to be done? It has already been said, a simple wrapper for that script is no option. I can only guess, I try nevertheless:

- UI work to manage credentials and accounts (if already included in system settings linking those)
- a background deamon to sync data in regular intervalls
- backend changes to display the data retrieved from a sync
- backend changes to deliver data to sync
- data validation to make sure data format matches card dav format, for data entered in address book app, and for data pulled by sync (very tricky, because I am guess not all providers stick 100% to the format)
- ???

**Comment by mardy** [comment]
> This is becoming silly. Is there any estimate on how much of work this would be. Would a bounty help?

There are two paths to solve this issue:
1. As @Danfro mentions, one can use a script that invokes syncevolution; then this solution can be improved by making the script execute at regular times, and maybe get controlled via the UI. I'm not involved in this solution, but I think I've seen some script circulating in the forums and in the comments in github.
2. Switching the contacts backend to qtcontacts-sqlite, which is the backend used by SailfishOS, and then use their plugins for synchronisation. They have plugins for carddav, google, and more.

I'm working on solution 2. I'm tracking the progress in https://github.com/ubports/ubuntu-touch/issues/997
As you can see, there are *many* components involved, and I'm the only one working on this path, in my very limited spare time. A bounty would not help me, because I'm already dedicating as much of my time as possible to this task; however, a bounty might help to convince additional developers to join the "fun".

Keep in mind, though, that we don't just need *any* developer: it should be one experienced with Qt and QML, at the very least. And then I would need to find time to explain him what I've done so far and how to proceed. And coordinate the work so that we don't step on each other. So, unless it's a developer who can spend *a lot* of time on this, a bounty would not be beneficial at all: a developer who would work on this stuff for only three hours per week would only make things even slower.

**Comment by myxor** [comment]
@mardy  are you still working on this? Is there any progress which you can share?

**Comment by mardy** [comment]
> @mardy are you still working on this? Is there any progress which you can share?

Yes, just yesterday evening I got the Google contact synchronisation to work. :-)

My plan now is to wait for OTA 19 to be released (should be a matter of days, hopefully) and then as soon as the next development cycle opens merge my changes in. As a first step, I'll try to get in the changes in the backend and in the Google account; I'm tempted to postpone the addition of the carddav plugin to the the cycle after the next one (that is, to get it into OTA 21) because I expect that on the cycle that leads to OTA 20 I will be busy fixing regressions: the changes are so many and so deep, that they'll keep me busy for a long while. But should things go better than I expect, then of course I'll try to get the carddav backend accepted in OTA 20 as well. :-)

**Comment by myxor** [comment]
That are really great news! Thanks for your dedication.

As you are talking about Google contact synchronisation a question comes to my mind: Does this work with regular CardDav endpoints (e.g. Nextcloud) as well?

**Comment by mardy** [comment]
> As you are talking about Google contact synchronisation a question comes to my mind: Does this work with regular CardDav endpoints (e.g. Nextcloud) as well?

No, Google uses its own protocol, so it won't work with Nextcloud. But the plugin to support CardDav is ready, it's just that I'm afraid that by adding it now we risk breaking other things.

**Comment by UniversalSuperBox** [comment]
This repository has moved to GitLab. You may find this request on GitLab at the following URL:

https://gitlab.com/ubports/core/address-book-app/-/issues/3
